use_frameworks!

platform :ios, '8.0'

target 'HarpUIKit_Example' do
  
#  pod 'HarpUIKit', :path => '../'

  pod 'JXTAlertManager'
  
  pod 'SVProgressHUD'
  
  pod 'MJRefresh'
  
  #pod 'MMDrawerController', '~> 0.5.7'
  
  pod 'LGSideMenuController'

end

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
end
end
end
end
